In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Electronic_sales_Sep2023-Sep2024.csv")

In [ ]:
df.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer ID        20000 non-null  int64
 1   Age                20000 non-null  int64
 2   Gender             19999 non-null  object
 3   Loyalty Member     20000 non-null  object
 4   Product Type       20000 non-null  object
 5   SKU                20000 non-null  object
 6   Rating             20000 non-null  int64
 7   Order Status       20000 non-null  object
 8   Payment Method     20000 non-null  object
 9   Total Price        20000 non-null  float64
 10  Unit Price         20000 non-null  float64
 11  Quantity           20000 non-null  int64
 12  Purchase Date      20000 non-null  object
 13  Shipping Type      20000 non-null  object
 14  Add-ons Purchased  15132 non-null  object
 15  Add-on Total       20000 non-null  float64
dtypes: float64(3), int64(4), object(9)
memory usage: 2.4+ MB

In [ ]:
df.shape

(20000, 16)

In [ ]:
print(df.columns)

Index(['Customer ID', 'Age', 'Gender', 'Loyalty Member', 'Product Type', 'SKU',
       'Rating', 'Order Status', 'Payment Method', 'Total Price', 'Unit Price',
       'Quantity', 'Purchase Date', 'Shipping Type', 'Add-ons Purchased',
       'Add-on Total'],
      dtype='object')

In [ ]:
df.isnull().sum()

Customer ID             0
Age                     0
Gender                  1
Loyalty Member          0
Product Type            0
SKU                     0
Rating                  0
Order Status            0
Payment Method          0
Total Price             0
Unit Price              0
Quantity                0
Purchase Date           0
Shipping Type           0
Add-ons Purchased    4868
Add-on Total            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df["Gender"].isnull()]

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
19999,19998,27,NaN,Yes,Laptop,LTP123,4,Completed,Bank Transfer,674.32,674.32,1,2024-01-29,Expedited,NaN,0.0

In [ ]:
df["Gender"] = df["Gender"].fillna("Unknown")

In [ ]:
df["Gender"].isnull().sum()

np.int64(0)

In [ ]:
df["Add-ons Purchased"].isnull().sum()

np.int64(4868)

In [ ]:
df["Add-ons Purchased"] = df["Add-ons Purchased"].fillna("No Add-on")

In [ ]:
df["Add-ons Purchased"].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Customer ID          0
Age                  0
Gender               0
Loyalty Member       0
Product Type         0
SKU                  0
Rating               0
Order Status         0
Payment Method       0
Total Price          0
Unit Price           0
Quantity             0
Purchase Date        0
Shipping Type        0
Add-ons Purchased    0
Add-on Total         0
dtype: int64

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
print(df["Payment Method"].unique())

['Credit Card' 'Paypal' 'Cash' 'Debit Card' 'Bank Transfer' 'PayPal']

In [ ]:
df["Payment Method"] = df["Payment Method"].replace({
    "Paypal": "PayPal"
})

In [ ]:
print(df["Payment Method"].unique())

['Credit Card' 'PayPal' 'Cash' 'Debit Card' 'Bank Transfer']

In [ ]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
print(df["Purchase Date"].dtype)

object

In [ ]:
df["Purchase Date"] = pd.to_datetime(df["Purchase Date"])

In [ ]:
print(df["Purchase Date"].dtype)

datetime64[ns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer ID        20000 non-null  int64
 1   Age                20000 non-null  int64
 2   Gender             20000 non-null  object
 3   Loyalty Member     20000 non-null  object
 4   Product Type       20000 non-null  object
 5   SKU                20000 non-null  object
 6   Rating             20000 non-null  int64
 7   Order Status       20000 non-null  object
 8   Payment Method     20000 non-null  object
 9   Total Price        20000 non-null  float64
 10  Unit Price         20000 non-null  float64
 11  Quantity           20000 non-null  int64
 12  Purchase Date      20000 non-null  datetime64[ns]
 13  Shipping Type      20000 non-null  object
 14  Add-ons Purchased  20000 non-null  object
 15  Add-on Total       20000 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(8)
memory usage: 2.4+ MB

In [ ]:
print(df["Age"].min())
print(df["Age"].max())

18
80

In [ ]:
print(df["Quantity"].min())
print(df["Quantity"].max())

1
10

In [ ]:
print(df["Unit Price"].min())
print(df["Total Price"].min())

20.75
20.75

In [ ]:
df.to_csv("Electronic_Sales_Cleaned.csv", index=False)

In [ ]:
from google.colab import files

files.download("Electronic_Sales_Cleaned.csv")